#Configuracion de Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mediappbd}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bar2005XP}
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

#Eliminando Warnings que aparecen por tema de Spring boot 3
spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL
spring.jpa.open-in-view=false

#Habilitando Virtual Threads
spring.threads.virtual.enabled=true

jwt.secret=${JWT_SECRET:aEIu9S7cvZUnPJWezau3rKUCxj4BLtpCVzhVSyam93prJOxofs7688P0OD5tmTIsLL6u7G9HpXvT}

# Keycloak Admin Client
keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:9595}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:mediapp}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:mediapp-backend}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:sNZ7TT49tV8kJyxEcfH2zboBJq4llxNj}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:mitotest21@gmail.com}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:123}
